// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5TqrZVg4w9SmsFO8_cJzx8kwKOYFQVvE',
    appId: '1:64943086962:web:6f67f28f03136c6d2011eb',
    messagingSenderId: '64943086962',
    projectId: 'admin-pajak',
    authDomain: 'admin-pajak.firebaseapp.com',
    storageBucket: 'admin-pajak.firebasestorage.app',
    measurementId: 'G-PLDW0JDZGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcL4cNwpiZIIhdk7GfCZxH3B0YFtem5WU',
    appId: '1:64943086962:android:32e33ddf971b562a2011eb',
    messagingSenderId: '64943086962',
    projectId: 'admin-pajak',
    storageBucket: 'admin-pajak.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBioi17hAY7VTsTtUqjHyxQbYyL4g4eJZ0',
    appId: '1:64943086962:ios:7ce32714829bf1582011eb',
    messagingSenderId: '64943086962',
    projectId: 'admin-pajak',
    storageBucket: 'admin-pajak.firebasestorage.app',
    iosBundleId: 'com.example.administrasiPeserta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBioi17hAY7VTsTtUqjHyxQbYyL4g4eJZ0',
    appId: '1:64943086962:ios:7ce32714829bf1582011eb',
    messagingSenderId: '64943086962',
    projectId: 'admin-pajak',
    storageBucket: 'admin-pajak.firebasestorage.app',
    iosBundleId: 'com.example.administrasiPeserta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5TqrZVg4w9SmsFO8_cJzx8kwKOYFQVvE',
    appId: '1:64943086962:web:0367a20fa514da562011eb',
    messagingSenderId: '64943086962',
    projectId: 'admin-pajak',
    authDomain: 'admin-pajak.firebaseapp.com',
    storageBucket: 'admin-pajak.firebasestorage.app',
    measurementId: 'G-2VNLG6YZBL',
  );

}